export const singleCardSchema = {
  startDate: Zod.string().nonempty("Start date is required"),
  endDate: Zod.string().nonempty("End date is required"),
  cardLimit: Zod.number().min(1, "Card limit must be at least 1"),
  field1: Zod.string().optional(),
  field2: Zod.string().optional(),
  notes: Zod.string().optional(),
  firstName: Zod.string().nonempty("First name is required"),
  lastName: Zod.string().nonempty("Last name is required"),
  employeeID: Zod.string().nonempty("Employee ID is required"),
  emailID: Zod.string().email("Invalid email address"),
  phoneNumber: Zod.string().nonempty("Phone number is required"),
  phoneNumberMasked: Zod.string().optional(),
  error: Zod.any().optional(),
  previewVisible: Zod.boolean().optional(),
  createDetails: Zod.any().optional(),
  phoneCode: Zod.string().default("+1"),
  reqId: Zod.string().optional().nullable(),
};
